name: ocrappnew
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  crop_your_image: ^0.7.1
  camera: ^0.10.5+9
  image_picker: ^1.0.7
  tflite_flutter: ^0.11.0
  image: ^4.1.7
  cupertino_icons: ^1.0.8
  fluttertoast: ^8.2.2
  shared_preferences: ^2.2.2
  pdf: ^3.10.0
  printing: ^5.9.1
  path_provider: ^2.1.1
  share_plus: ^7.0.0
  permission_handler: ^11.0.0
  intl: ^0.18.1
  path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.0
  flutter_lints: ^5.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/AbyssinicaSIL-Regular.ttf
    - assets/models/new_amharic_yolo8s_last.tflite
    - assets/models/ocr_fixed_tcn_ctc.tflite
    - assets/data/awam_vocab.txt
  fonts:
    - family: AbyssinicaSIL
      fonts:
        - asset: assets/fonts/AbyssinicaSIL-Regular.ttf
